"""
fixtures.py — Realistic resume text fixtures for testing.

Rules:
  - All fixtures are crafted to represent real PDF-extraction output.
  - Fixtures include deliberate artifacts (spaced chars, Unicode dashes, etc.)
  - Ground truth dicts reflect what correct parsing should produce.
  - Fixtures are immutable — never auto-generated by the parser.
"""

from typing import Dict, List, Any

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 1: Standard resume — clean, well-structured
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_STANDARD = """Priya Sharma
priya.sharma@email.com | +91-9876543210 | linkedin.com/in/priyasharma | Bangalore, India

SUMMARY
Results-driven software engineer with 3 years of experience in full-stack development.

EDUCATION
B.Tech in Computer Science
IIT Bombay | 2017 - 2021 | CGPA: 8.7/10

EXPERIENCE
Software Engineer | Infosys Ltd | Bangalore | Jun 2021 - Present
- Developed RESTful APIs using Python and Django serving 50K daily users
- Reduced latency by 35% through Redis caching implementation
- Led migration from monolith to microservices architecture

Intern | Wipro Technologies | Mumbai | May 2020 - Jul 2020
- Built data pipeline using Apache Kafka and PySpark

PROJECTS
Resume Parser
- Built NLP-based resume parser using Python and spaCy
- Deployed on AWS EC2 with Docker containerization

SKILLS
Languages: Python, Java, JavaScript
Frameworks: Django, React, Node.js
Databases: MySQL, MongoDB, Redis
Tools: Docker, Git, AWS

CERTIFICATIONS
AWS Certified Solutions Architect | Amazon | 2022
Google Cloud Professional Data Engineer | Google | 2023

LEADERSHIP
Technical Head | Coding Club IIT Bombay | 2019 - 2021
- Organized 5 hackathons with 500+ participants
- Mentored 30+ junior students in competitive programming
"""

FIXTURE_STANDARD_GROUND_TRUTH: Dict[str, Any] = {
    "contact": {
        "name": "Priya Sharma",
        "email": "priya.sharma@email.com",
    },
    "education_count": 1,
    "experience_count": 2,
    "certifications_count": 2,
    "leadership_count": 1,
    "skills_not_empty": True,
}

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 2: Combined header — "Positions of Responsibility / Extracurriculars"
# Tests that leadership is NOT lost to other_section or certifications
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_COMBINED_HEADER = """Rahul Mehta
rahul.mehta@gmail.com | 9876501234

EDUCATION
B.Tech, Mechanical Engineering
NIT Trichy | 2018 – 2022 | CGPA: 7.9

EXPERIENCE
Graduate Engineer Trainee | Tata Motors | Pune | Jul 2022 – Present
- Worked on engine assembly line optimization
- Reduced defect rate by 12%

CERTIFICATIONS
Lean Six Sigma Green Belt | IASSC | 2023
AutoCAD Certified Professional | Autodesk | 2022

Positions of Responsibility / Extracurriculars
Vice President | Mechanical Engineering Society | 2021 – 2022
- Led team of 15 in organizing TechFest with 2000+ attendees
Secretary | NSS Unit | 2019 – 2021
- Coordinated 200+ hours of community service

SKILLS
Technical: AutoCAD, CATIA, MATLAB, SolidWorks
Programming: Python, MATLAB
"""

FIXTURE_COMBINED_HEADER_GROUND_TRUTH: Dict[str, Any] = {
    "leadership_count_min": 1,                  # leadership must have entries
    "certifications_not_absorb_leadership": True,  # VP and Secretary NOT in certs
    "leadership_keywords": ["Vice President", "Secretary"],
}

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 3: Year-prefixed education lines
# Tests year-prefix handling: "2019 – 2023   B.Tech, Computer Science"
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_YEAR_PREFIX_EDUCATION = """Arjun Nair
arjun.nair@outlook.com | Kerala, India

EDUCATION
2019 – 2023   B.Tech, Computer Science and Engineering
               College of Engineering Trivandrum | CGPA: 8.2

2017 – 2019   Higher Secondary (Class XII)
               Kerala HSE Board | 94.5%

WORK EXPERIENCE
Software Developer | Zoho Corporation | Chennai | Aug 2023 – Present
- Built features for CRM module using Java and React

TECHNICAL SKILLS
Languages: Java, Python, C, JavaScript
Web: React, HTML, CSS, Spring Boot
Database: MySQL, PostgreSQL

PROJECTS
E-Commerce Platform
- Full-stack app with React frontend and Spring Boot backend
- Integrated Razorpay payment gateway
"""

FIXTURE_YEAR_PREFIX_EDUCATION_GROUND_TRUTH: Dict[str, Any] = {
    "education_count": 2,
    "education_has_start_dates": True,
    "first_edu_start": "2019",
    "first_edu_end": "2023",
}

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 4: Certifications followed immediately by leadership
# This is the exact failure scenario — certifications must NOT absorb leadership
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_CERT_THEN_LEADERSHIP = """Sneha Gupta
sneha.g@gmail.com | Mumbai | +91 8765432109

Education
MBA, Finance | IIM Ahmedabad | 2021 – 2023
B.Com | Mumbai University | 2018 – 2021

Professional Experience
Financial Analyst | HDFC Bank | Mumbai | Aug 2023 – Present
- Analyzed portfolio worth INR 500 Cr
- Built Excel models for risk assessment

Certifications
CFA Level 1 | CFA Institute | 2022
Financial Risk Manager (FRM) | GARP | 2023

Leadership Experience
President | Finance Club, IIM Ahmedabad | 2022 – 2023
- Managed club budget of INR 5 Lakhs
- Organized Annual Finance Conclave with 300+ attendees
Volunteer | Teach For India | 2020
- Taught mathematics to underprivileged students

Skills
Financial Modeling, Excel, Python, SQL, Bloomberg Terminal
"""

FIXTURE_CERT_THEN_LEADERSHIP_GROUND_TRUTH: Dict[str, Any] = {
    "certifications_count": 2,
    "leadership_count_min": 1,
    "leadership_not_empty": True,
    "certifications_line_count_max": 15,  # certifications block shouldn't be huge
}

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 5: PDF artifact resume — spaced characters, Unicode dashes
# Tests normalization pipeline
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_PDF_ARTIFACTS = """Vikram Singh
vikram.singh@email.com

E d u c a t i o n
B.Tech in Computer Science \u2013 IIT Delhi \u2013 2020\u20132024

W o r k   E x p e r i e n c e
Software Engineer \u2014 Google India \u2014 Jun 2024 \u2013 Present
\u2022 Built scalable backend services using Go and gRPC
\u2022 Improved system throughput by 40%

S k i l l s
Go, Python, gRPC, Kubernetes, PostgreSQL

C e r t i f i c a t i o n s
Google Cloud Professional \u2013 Google \u2013 2024

L e a d e r s h i p
Technical Secretary | Computer Science Association | 2022\u20132024
"""

FIXTURE_PDF_ARTIFACTS_GROUND_TRUTH: Dict[str, Any] = {
    "education_not_empty": True,
    "experience_not_empty": True,
    "leadership_not_empty": True,
    "certifications_not_empty": True,
}

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 6: No headers at all — bare resume
# Tests graceful handling with all content going to contact/other
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_NO_HEADERS = """John Doe
john.doe@email.com
+1 555-0100
New York, NY

3 years of Python development experience.
Built several web applications using Django and React.
Proficient in SQL, AWS, and Docker.
"""

FIXTURE_NO_HEADERS_GROUND_TRUTH: Dict[str, Any] = {
    "no_crash": True,
    "contact_email_found": True,
}

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 7: Multiple unrecognized headers
# All unrecognized headers go to other_section, no bleeding
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_UNRECOGNIZED_HEADERS = """Maria Lopez
maria@email.com

BACKGROUND
Software engineer with 5 years in fintech.

TECHNICAL COMPETENCIES
Python, Java, React, AWS

NOTABLE ACHIEVEMENTS
- Led platform migration saving $2M annually
- Received Employee of the Year 2023

PROFESSIONAL AFFILIATIONS
IEEE Member since 2019
ACM Member since 2020

REFERENCES
Available on request
"""

# ─────────────────────────────────────────────────────────────────────────────
# FIXTURE 8: Dense resume — all sections present, long bullets
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_DENSE = """Aditya Kumar
aditya.kumar@protonmail.com | github.com/adityak | linkedin.com/in/adityakumar
Hyderabad, India | +91-9000000001

PROFESSIONAL SUMMARY
Senior software engineer with 6+ years building distributed systems at scale.
Expertise in Python, Golang, and cloud-native architectures.

EDUCATION
M.Tech, Computer Science | IIT Hyderabad | 2016 – 2018
B.Tech, Information Technology | JNTU Hyderabad | 2012 – 2016

WORK EXPERIENCE
Senior Software Engineer | Amazon | Hyderabad | Mar 2020 – Present
- Designed and implemented order routing service handling 1M+ req/day
- Reduced P99 latency from 800ms to 120ms using async processing
- Mentored team of 4 junior engineers

Software Engineer | Flipkart | Bangalore | Jun 2018 – Feb 2020
- Built real-time inventory sync system using Kafka and Flink
- Developed seller analytics dashboard with React and GraphQL

PROJECTS
Distributed Task Scheduler
- Built using Python, Redis, and Celery; handles 100K tasks/day
- Open sourced with 500+ GitHub stars

ML Pipeline Framework
- Automated ML training pipeline with MLflow and Airflow
- Reduced model deployment time from 2 weeks to 2 days

TECHNICAL SKILLS
Languages: Python, Go, Java, JavaScript, SQL
Frameworks: FastAPI, Django, React, Kafka, Flink
Cloud: AWS (EC2, S3, Lambda, SQS, RDS), GCP
Tools: Docker, Kubernetes, Terraform, Airflow, MLflow, Git
Databases: PostgreSQL, MySQL, Redis, MongoDB, Elasticsearch

CERTIFICATIONS
AWS Certified Solutions Architect – Professional | Amazon | 2022
AWS Certified Developer – Associate | Amazon | 2021
Kubernetes Administrator (CKA) | CNCF | 2023

LEADERSHIP & ACTIVITIES
Tech Lead | Python Hyderabad User Group | 2021 – Present
- Organizes monthly meetups with 100+ attendees
- Delivered 8 technical talks on distributed systems

Mentor | GirlScript Summer of Code | 2020, 2021
- Mentored 12 open source contributors

ACHIEVEMENTS
Best Paper Award | ICDCS 2019
Spot Award Q2 2022 | Amazon
"""

FIXTURE_DENSE_GROUND_TRUTH: Dict[str, Any] = {
    "education_count": 2,
    "experience_count": 2,
    "certifications_count": 3,
    "leadership_count_min": 1,
    "projects_count_min": 1,
    "contact_name": "Aditya Kumar",
    "contact_email": "aditya.kumar@protonmail.com",
}


# ─────────────────────────────────────────────────────────────────────────────
# Registry of all fixtures
# ─────────────────────────────────────────────────────────────────────────────

ALL_FIXTURES: List[Dict[str, Any]] = [
    {"name": "standard",             "text": FIXTURE_STANDARD,             "truth": FIXTURE_STANDARD_GROUND_TRUTH},
    {"name": "combined_header",      "text": FIXTURE_COMBINED_HEADER,      "truth": FIXTURE_COMBINED_HEADER_GROUND_TRUTH},
    {"name": "year_prefix_education","text": FIXTURE_YEAR_PREFIX_EDUCATION,"truth": FIXTURE_YEAR_PREFIX_EDUCATION_GROUND_TRUTH},
    {"name": "cert_then_leadership", "text": FIXTURE_CERT_THEN_LEADERSHIP, "truth": FIXTURE_CERT_THEN_LEADERSHIP_GROUND_TRUTH},
    {"name": "pdf_artifacts",        "text": FIXTURE_PDF_ARTIFACTS,        "truth": FIXTURE_PDF_ARTIFACTS_GROUND_TRUTH},
    {"name": "no_headers",           "text": FIXTURE_NO_HEADERS,           "truth": FIXTURE_NO_HEADERS_GROUND_TRUTH},
    {"name": "dense",                "text": FIXTURE_DENSE,                "truth": FIXTURE_DENSE_GROUND_TRUTH},
]
