"""initial_schema_phase4

Revision ID: bdd4230e58b4
Revises: 
Create Date: 2026-06-25 07:27:53.001798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd4230e58b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('parsed_json', sa.Text(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_uploaded_at'), 'resumes', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index('ix_resumes_user_uploaded', 'resumes', ['user_id', 'uploaded_at'], unique=False)
    op.create_table('ats_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=False),
    sa.Column('ats_breakdown', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ats_reports_created_at'), 'ats_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_ats_reports_id'), 'ats_reports', ['id'], unique=False)
    op.create_index('ix_ats_reports_resume_created', 'ats_reports', ['resume_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ats_reports_resume_id'), 'ats_reports', ['resume_id'], unique=False)
    op.create_table('jd_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.Text(), nullable=False),
    sa.Column('missing_skills', sa.Text(), nullable=False),
    sa.Column('learning_roadmap', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_reports_created_at'), 'jd_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_jd_reports_id'), 'jd_reports', ['id'], unique=False)
    op.create_index('ix_jd_reports_resume_created', 'jd_reports', ['resume_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_jd_reports_resume_id'), 'jd_reports', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jd_reports_resume_id'), table_name='jd_reports')
    op.drop_index('ix_jd_reports_resume_created', table_name='jd_reports')
    op.drop_index(op.f('ix_jd_reports_id'), table_name='jd_reports')
    op.drop_index(op.f('ix_jd_reports_created_at'), table_name='jd_reports')
    op.drop_table('jd_reports')
    op.drop_index(op.f('ix_ats_reports_resume_id'), table_name='ats_reports')
    op.drop_index('ix_ats_reports_resume_created', table_name='ats_reports')
    op.drop_index(op.f('ix_ats_reports_id'), table_name='ats_reports')
    op.drop_index(op.f('ix_ats_reports_created_at'), table_name='ats_reports')
    op.drop_table('ats_reports')
    op.drop_index('ix_resumes_user_uploaded', table_name='resumes')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_uploaded_at'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
